// boxes-data.jsx — sample Mystery Box fixtures

const STATUSES = ['Draft', 'Finalized', 'Printed', 'Dispatched'];

// Sample boxes — previously dispatched / in progress
const MYSTERY_BOXES = [
  {
    id: 'MB-2026-1284',
    region: 'Frisco',
    address: '1420 Legacy Dr · Frisco, TX 75034',
    dispatchDate: '2026-04-18',
    families: 32,
    meals4p: 3,
    meals2p: 1,
    recipesCount: 4,
    status: 'Dispatched',
    qrUrl: 'lovepacs.org/b/mb-fri-1284',
    event: 'Christmas Distribution 2026',
    items: [
      { id: 'spaghetti', qty: 2 }, { id: 'marinara', qty: 2 }, { id: 'tuna', qty: 4 },
      { id: 'blackbeans', qty: 3 }, { id: 'ricewhite', qty: 1 }, { id: 'cornkernels', qty: 2 },
      { id: 'chickenbroth', qty: 2 }, { id: 'tomatoes', qty: 2 },
    ],
    recipes: ['pantry-spag', 'arroz-frijol', 'oven-bake', 'cowboy'],
    printed: true,
    dispatchedAt: '2026-04-18 09:14',
  },
  {
    id: 'MB-2026-1283',
    region: 'Plano',
    address: '3801 W Parker Rd · Plano, TX 75023',
    dispatchDate: '2026-04-18',
    families: 18,
    meals4p: 2,
    meals2p: 2,
    recipesCount: 4,
    status: 'Dispatched',
    qrUrl: 'lovepacs.org/b/mb-pln-1283',
    event: 'Christmas Distribution 2026',
    items: [
      { id: 'spaghetti', qty: 1 }, { id: 'marinara', qty: 1 }, { id: 'tuna', qty: 2 },
      { id: 'blackbeans', qty: 2 }, { id: 'ricewhite', qty: 1 }, { id: 'cornkernels', qty: 1 },
      { id: 'chickenbroth', qty: 1 }, { id: 'tomatoes', qty: 1 }, { id: 'peaches', qty: 1 },
    ],
    recipes: ['pantry-spag', 'arroz-frijol', 'oven-bake', 'cowboy'],
    printed: true,
    dispatchedAt: '2026-04-18 08:41',
  },
  {
    id: 'MB-2026-1282',
    region: 'McKinney',
    address: '2200 W White Ave · McKinney, TX 75071',
    dispatchDate: '2026-04-17',
    families: 24,
    meals4p: 3,
    meals2p: 1,
    recipesCount: 4,
    status: 'Printed',
    qrUrl: 'lovepacs.org/b/mb-mck-1282',
    event: 'School partnership',
    items: [
      { id: 'spaghetti', qty: 1 }, { id: 'marinara', qty: 1 }, { id: 'tuna', qty: 2 },
      { id: 'blackbeans', qty: 2 }, { id: 'ricewhite', qty: 2 }, { id: 'cornkernels', qty: 1 },
      { id: 'chickenbroth', qty: 1 }, { id: 'oats', qty: 1 }, { id: 'peanutbutter', qty: 1 },
    ],
    recipes: ['pantry-spag', 'arroz-frijol', 'oven-bake', 'cowboy'],
    printed: true,
  },
  {
    id: 'MB-2026-1281',
    region: 'Little Elm',
    address: '301 S Main St · Little Elm, TX 75068',
    dispatchDate: '2026-04-17',
    families: 14,
    meals4p: 2,
    meals2p: 2,
    recipesCount: 4,
    status: 'Finalized',
    qrUrl: 'lovepacs.org/b/mb-lel-1281',
    event: 'Standard packs',
    items: [
      { id: 'spaghetti', qty: 1 }, { id: 'marinara', qty: 1 }, { id: 'tuna', qty: 2 },
      { id: 'blackbeans', qty: 1 }, { id: 'ricewhite', qty: 1 }, { id: 'cornkernels', qty: 1 },
    ],
    recipes: ['pantry-spag', 'arroz-frijol', 'oven-bake', 'cowboy'],
    printed: false,
  },
  {
    id: 'MB-2026-1280',
    region: 'Frisco',
    address: '—',
    dispatchDate: '2026-04-19',
    families: 20,
    meals4p: 3,
    meals2p: 0,
    recipesCount: 3,
    status: 'Draft',
    qrUrl: null,
    event: 'Standard packs',
    items: [
      { id: 'spaghetti', qty: 1 }, { id: 'marinara', qty: 1 }, { id: 'blackbeans', qty: 1 },
      { id: 'ricewhite', qty: 1 }, { id: 'cornkernels', qty: 1 },
    ],
    recipes: ['pantry-spag', 'arroz-frijol', 'cowboy'],
    printed: false,
  },
  {
    id: 'MB-2026-1279',
    region: 'Prosper',
    address: '605 E First St · Prosper, TX 75078',
    dispatchDate: '2026-04-16',
    families: 11,
    meals4p: 1,
    meals2p: 3,
    recipesCount: 4,
    status: 'Dispatched',
    qrUrl: 'lovepacs.org/b/mb-prs-1279',
    event: 'Church partnership',
    items: [
      { id: 'spaghetti', qty: 1 }, { id: 'marinara', qty: 1 }, { id: 'tuna', qty: 2 },
      { id: 'oats', qty: 1 }, { id: 'peanutbutter', qty: 1 }, { id: 'peaches', qty: 1 },
    ],
    recipes: ['pantry-spag', 'arroz-frijol', 'oven-bake', 'cowboy'],
    printed: true,
    dispatchedAt: '2026-04-16 11:02',
  },
  {
    id: 'MB-2026-1278',
    region: 'Allen',
    address: '900 Central Expy S · Allen, TX 75013',
    dispatchDate: '2026-04-15',
    families: 28,
    meals4p: 2,
    meals2p: 2,
    recipesCount: 4,
    status: 'Dispatched',
    qrUrl: 'lovepacs.org/b/mb-aln-1278',
    event: 'Standard packs',
    items: [
      { id: 'spaghetti', qty: 2 }, { id: 'marinara', qty: 2 }, { id: 'tuna', qty: 3 },
      { id: 'blackbeans', qty: 2 }, { id: 'ricewhite', qty: 2 }, { id: 'cornkernels', qty: 2 },
    ],
    recipes: ['pantry-spag', 'arroz-frijol', 'oven-bake', 'cowboy'],
    printed: true,
    dispatchedAt: '2026-04-15 10:30',
  },
  {
    id: 'MB-2026-1277',
    region: 'Plano',
    address: '1600 Preston Rd · Plano, TX 75093',
    dispatchDate: '2026-04-15',
    families: 9,
    meals4p: 2,
    meals2p: 1,
    recipesCount: 3,
    status: 'Dispatched',
    qrUrl: 'lovepacs.org/b/mb-pln-1277',
    event: 'Standard packs',
    items: [
      { id: 'spaghetti', qty: 1 }, { id: 'marinara', qty: 1 }, { id: 'blackbeans', qty: 1 },
      { id: 'ricewhite', qty: 1 },
    ],
    recipes: ['pantry-spag', 'arroz-frijol', 'oven-bake'],
    printed: true,
    dispatchedAt: '2026-04-15 09:02',
  },
];

window.STATUSES = STATUSES;
window.MYSTERY_BOXES = MYSTERY_BOXES;
